<dec f='include/python3.5m/pyerrors.h' l='291' type='void _PyErr_BadInternalCall(const char * filename, int lineno)'/>
