<dec f='include/python3.5m/pyerrors.h' l='88' type='void PyErr_Fetch(PyObject ** , PyObject ** , PyObject ** )'/>
<use f='tensorflow/tensorflow/python/lib/core/py_util.cc' l='99' u='c' c='_ZN10tensorflow16PyExceptionFetchEv'/>
