<dec f='include/python3.5m/pyerrors.h' l='245' type='PyObject * PyErr_Format(PyObject * exception, const char * format)'/>
<use f='tensorflow/tensorflow/python/lib/core/bfloat16.cc' l='137' u='c' c='_ZN10tensorflow12_GLOBAL__N_110AsBfloat16EP7_objectPNS_8bfloat16E'/>
<use f='tensorflow/tensorflow/python/lib/core/bfloat16.cc' l='605' u='c' c='_ZN10tensorflow12_GLOBAL__N_110InitializeEv'/>
