<dec f='include/python3.5m/pyerrors.h' l='114' type='void PyErr_NormalizeException(PyObject ** , PyObject ** , PyObject ** )'/>
<use f='tensorflow/tensorflow/python/lib/core/py_util.cc' l='100' u='c' c='_ZN10tensorflow16PyExceptionFetchEv'/>
