<dec f='tensorflow/tensorflow/python/lib/core/py_exception_registry.h' l='64' type='tensorflow::PyExceptionRegistry *'/>
<def f='tensorflow/tensorflow/python/lib/core/py_exception_registry.cc' l='22' type='tensorflow::PyExceptionRegistry *'/>
<use f='tensorflow/tensorflow/python/lib/core/py_exception_registry.cc' l='25' u='r' c='_ZN10tensorflow19PyExceptionRegistry4InitEP7_object'/>
<use f='tensorflow/tensorflow/python/lib/core/py_exception_registry.cc' l='26' u='w' c='_ZN10tensorflow19PyExceptionRegistry4InitEP7_object'/>
<use f='tensorflow/tensorflow/python/lib/core/py_exception_registry.cc' l='34' u='r' c='_ZN10tensorflow19PyExceptionRegistry4InitEP7_object'/>
<use f='tensorflow/tensorflow/python/lib/core/py_exception_registry.cc' l='42' u='r' c='_ZN10tensorflow19PyExceptionRegistry6LookupE7TF_Code'/>
<use f='tensorflow/tensorflow/python/lib/core/py_exception_registry.cc' l='45' u='r' c='_ZN10tensorflow19PyExceptionRegistry6LookupE7TF_Code'/>
<use f='tensorflow/tensorflow/python/lib/core/py_exception_registry.cc' l='45' u='r' c='_ZN10tensorflow19PyExceptionRegistry6LookupE7TF_Code'/>
<use f='tensorflow/tensorflow/python/lib/core/py_exception_registry.cc' l='47' u='r' c='_ZN10tensorflow19PyExceptionRegistry6LookupE7TF_Code'/>
