<dec f='include/python3.5m/pyerrors.h' l='128' type='void _PyErr_ChainExceptions(PyObject * , PyObject * , PyObject * )'/>
