<dec f='include/python3.5m/pyerrors.h' l='149' type='PyObject *'/>
<use f='tensorflow/tensorflow/python/eager/pywrap_tfe_src.cc' l='611' u='r' c='_Z29TFE_Py_RegisterExceptionClassP7_object'/>
<use f='tensorflow/tensorflow/python/eager/pywrap_tfe_src.cc' l='645' u='r' c='_Z37TFE_Py_RegisterFallbackExceptionClassP7_object'/>
