<dec f='tensorflow/tensorflow/python/lib/core/py_util.h' l='24' type='string tensorflow::PyExceptionFetch()'/>
<use f='tensorflow/tensorflow/python/lib/core/py_func.cc' l='192' u='c' c='_ZN10tensorflow12_GLOBAL__N_112DoCallPyFuncEPNS0_6PyCallEPb'/>
<use f='tensorflow/tensorflow/python/lib/core/py_func.cc' l='195' u='c' c='_ZN10tensorflow12_GLOBAL__N_112DoCallPyFuncEPNS0_6PyCallEPb'/>
<use f='tensorflow/tensorflow/python/lib/core/py_func.cc' l='197' u='c' c='_ZN10tensorflow12_GLOBAL__N_112DoCallPyFuncEPNS0_6PyCallEPb'/>
<use f='tensorflow/tensorflow/python/lib/core/py_func.cc' l='199' u='c' c='_ZN10tensorflow12_GLOBAL__N_112DoCallPyFuncEPNS0_6PyCallEPb'/>
<use f='tensorflow/tensorflow/python/lib/core/py_func.cc' l='203' u='c' c='_ZN10tensorflow12_GLOBAL__N_112DoCallPyFuncEPNS0_6PyCallEPb'/>
<doc f='tensorflow/tensorflow/python/lib/core/py_util.h' l='22'>// Fetch the exception message as a string. An exception must be set
// (PyErr_Occurred() must be true).</doc>
<use f='tensorflow/tensorflow/python/lib/core/py_seq_tensor.cc' l='108' u='c' c='_ZN10tensorflow12_GLOBAL__N_117InferShapeAndTypeEP7_objectPNS_11TensorShapeEPNS_8DataTypeE'/>
<def f='tensorflow/tensorflow/python/lib/core/py_util.cc' l='93' ll='123' type='string tensorflow::PyExceptionFetch()'/>
