<dec f='include/python3.5m/pyerrors.h' l='122' type='void PyException_SetCause(PyObject * , PyObject * )'/>
